In [1]:
import pandas as pd
import numpy as np

In [4]:
data_youtube = pd.read_csv(r'D:\Git_repository\dataEn_final_project\collect_data\datasets\raw_data\youtube_base_on_spotify.csv')
data_spotify = pd.read_csv(r'D:\Git_repository\dataEn_final_project\collect_data\datasets\raw_data\spotify.csv')
data_last_fm = pd.read_csv(r'D:\Git_repository\dataEn_final_project\collect_data\datasets\raw_data\last_fm_base_on_spotify.csv')

# Data Understanding and Cleaning (Spotify)

In [6]:
new_df = data_spotify.copy()
new_df.head(5)

,id,track_name,artist,album,popularity,release_date,spotify_url,preview_url,Genre
0,15cQVPbbwv0sZXrHRIAZeX,When I'm With You,NCT DREAM,DREAMSCAPE,74,2024-11-11,https://open.spotify.com/track/15cQVPbbwv0sZXr...,NaN,pop
1,3yDRcs0Y4pPzkvMbUfeF9H,Moonlit Floor (Kiss Me),LISA,Moonlit Floor (Kiss Me),79,2024-10-03,https://open.spotify.com/track/3yDRcs0Y4pPzkvM...,NaN,pop
2,7tI8dRuH2Yc6RuoTjxo4dU,Who,Jimin,MUSE,86,2024-07-19,https://open.spotify.com/track/7tI8dRuH2Yc6Ruo...,NaN,pop
3,7ov3TDp5D00Rnu5R1viX4w,New Woman (feat. ROSALÍA),"LISA, ROSALÍA",New Woman (feat. ROSALÍA),77,2024-08-15,https://open.spotify.com/track/7ov3TDp5D00Rnu5...,NaN,pop
4,2plbrEY59IikOBgBGLjaoe,Die With A Smile,"Lady Gaga, Bruno Mars",Die With A Smile,97,2024-08-16,https://open.spotify.com/track/2plbrEY59IikOBg...,NaN,pop

In [7]:
new_df = new_df.drop('preview_url', axis=1)

In [8]:
new_df.head(5)

,id,track_name,artist,album,popularity,release_date,spotify_url,Genre
0,15cQVPbbwv0sZXrHRIAZeX,When I'm With You,NCT DREAM,DREAMSCAPE,74,2024-11-11,https://open.spotify.com/track/15cQVPbbwv0sZXr...,pop
1,3yDRcs0Y4pPzkvMbUfeF9H,Moonlit Floor (Kiss Me),LISA,Moonlit Floor (Kiss Me),79,2024-10-03,https://open.spotify.com/track/3yDRcs0Y4pPzkvM...,pop
2,7tI8dRuH2Yc6RuoTjxo4dU,Who,Jimin,MUSE,86,2024-07-19,https://open.spotify.com/track/7tI8dRuH2Yc6Ruo...,pop
3,7ov3TDp5D00Rnu5R1viX4w,New Woman (feat. ROSALÍA),"LISA, ROSALÍA",New Woman (feat. ROSALÍA),77,2024-08-15,https://open.spotify.com/track/7ov3TDp5D00Rnu5...,pop
4,2plbrEY59IikOBgBGLjaoe,Die With A Smile,"Lady Gaga, Bruno Mars",Die With A Smile,97,2024-08-16,https://open.spotify.com/track/2plbrEY59IikOBg...,pop

In [9]:
new_df[new_df['album'].isna()]

,id,track_name,artist,album,popularity,release_date,spotify_url,Genre
3079,0V2passWyAXnON67kfAj7y,ABCD,NAYEON,NaN,68,2024-06-14,https://open.spotify.com/track/0V2passWyAXnON6...,k-pop

In [10]:
new_df.loc[3079,'album'] = 'NA'

In [14]:
new_df[new_df['album']=='NA']

,id,track_name,artist,album,popularity,release_date,spotify_url,Genre
3079,0V2passWyAXnON67kfAj7y,ABCD,NAYEON,NA,68,2024-06-14,https://open.spotify.com/track/0V2passWyAXnON6...,k-pop

In [15]:
new_df.isnull().sum()

id              0
track_name      0
artist          0
album           0
popularity      0
release_date    0
spotify_url     0
Genre           0
dtype: int64

In [ ]:
# Not run
years = []
months = []
days = []
for i in new_df.index:
  release_date = new_df.loc[i,'release_date']
  temp = release_date.split('-')
  if len(release_date) == 4:
    years.append(temp[0])
    months.append(np.NaN)
    days.append(np.NaN)
  elif len(release_date) == 7:
    years.append(temp[0])
    months.append(temp[1])
    days.append(np.NaN)
  else:
    years.append(temp[0])
    months.append(temp[1])
    days.append(temp[2])
new_df['year'] = years
new_df['month'] = months
new_df['day'] = days

In [ ]:
new_df

,id,track_name,artist,album,popularity,release_date,spotify_url,Genre
0,15cQVPbbwv0sZXrHRIAZeX,When I'm With You,NCT DREAM,DREAMSCAPE,74,2024-11-11,https://open.spotify.com/track/15cQVPbbwv0sZXr...,pop
1,3yDRcs0Y4pPzkvMbUfeF9H,Moonlit Floor (Kiss Me),LISA,Moonlit Floor (Kiss Me),79,2024-10-03,https://open.spotify.com/track/3yDRcs0Y4pPzkvM...,pop
2,7tI8dRuH2Yc6RuoTjxo4dU,Who,Jimin,MUSE,86,2024-07-19,https://open.spotify.com/track/7tI8dRuH2Yc6Ruo...,pop
3,7ov3TDp5D00Rnu5R1viX4w,New Woman (feat. ROSALÍA),"LISA, ROSALÍA",New Woman (feat. ROSALÍA),77,2024-08-15,https://open.spotify.com/track/7ov3TDp5D00Rnu5...,pop
4,2plbrEY59IikOBgBGLjaoe,Die With A Smile,"Lady Gaga, Bruno Mars",Die With A Smile,97,2024-08-16,https://open.spotify.com/track/2plbrEY59IikOBg...,pop
...,...,...,...,...,...,...,...,...
7212,70k5BJcKCA6raiC345tdSb,How To Save A Life - Techno Remix,Discotekk,How To Save A Life (Techno Remix),55,2023-09-15,https://open.spotify.com/track/70k5BJcKCA6raiC...,techno
7213,2T6DsaUYxwYeIyYTwD68ol,裸足の季節,Seiko Matsuda,BIBLE,33,1980,https://open.spotify.com/track/2T6DsaUYxwYeIyY...,techno
7214,0KCT63T5YEsW8pNnuhr9ZC,Light Up the Sky,The Prodigy,No Tourists,43,2018-11-02,https://open.spotify.com/track/0KCT63T5YEsW8pN...,techno
7215,7oAM2GxHCTKTLU3gXvkuuj,Die Welt Brennt,"Klangkuenstler, Obernauer",Die Welt Brennt,48,2023-02-03,https://open.spotify.com/track/7oAM2GxHCTKTLU3...,techno
7216,40hscplKySBPzeXEhfBy7E,Body Language - Original Remaster,"M.A.N.D.Y., Booka Shade",Body Language,42,2023-03-31,https://open.spotify.com/track/40hscplKySBPzeX...,techno

In [ ]:
new_df.to_csv('cleaned_data_spotify.csv', index=False)

# Data Understanding and Cleaning (Youtube)

In [5]:
df = data_youtube.copy()

In [6]:
df.head(5)

,song_name,video_id,title,artist,release_date,views,likes,comments,error
0,Shape of You Ed Sheeran,liTfD88dbCo,Ed Sheeran - Shape of You (Lyrics),7clouds,2024-12-13T19:33:36Z,1.617114e+07,87989.0,3379.0,NaN
1,Blinding Lights The Weeknd,XwxLwG2_Sxk,The Weeknd - Blinding Lights (Lyrics),7clouds,2020-03-01T18:09:07Z,1.424817e+08,1369380.0,35208.0,NaN
2,Dance Monkey Tones and I,q0hyYWKXF0Q,TONES AND I - DANCE MONKEY (OFFICIAL VIDEO),Tones And I,2019-06-24T22:01:36Z,2.212981e+09,16058425.0,392347.0,NaN
3,When I'm With You,qiaLTtDLB10,NCT DREAM 엔시티 드림 &#39;When I&#39;m With You&#3...,NCT DREAM,2024-11-18T15:00:59Z,1.356990e+06,76411.0,2642.0,NaN
4,Moonlit Floor (Kiss Me),pxGM_TOgHuM,LISA - MOONLIT FLOOR (Official Performance Video),LLOUD Official,2024-10-09T00:00:07Z,6.620069e+07,1310509.0,46314.0,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7220 entries, 0 to 7219
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   song_name     7220 non-null   object
 1   video_id      7206 non-null   object
 2   title         7206 non-null   object
 3   artist        7206 non-null   object
 4   release_date  7206 non-null   object
 5   views         7205 non-null   float64
 6   likes         7178 non-null   float64
 7   comments      7165 non-null   float64
 8   error         14 non-null     object
dtypes: float64(3), object(6)
memory usage: 507.8+ KB

In [8]:
df[df['error'].notnull()]

,song_name,video_id,title,artist,release_date,views,likes,comments,error
99,New Jeans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
1794,FRIENDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
2408,After Midnight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
2437,Charmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
2499,Advice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
2776,Fiebre (Prod. King DouDou),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: The read operation timed out
2867,BADGYAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
3069,Run BTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
3310,Stray Kids,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
4323,Friends,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
4478,Treasure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
6002,No Cigar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
6146,Kiss of Life,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'
7011,Imagineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unexpected error: 'videoId'

In [9]:
new_df  = df[df['error'].isna()].drop('error', axis=1)

In [10]:
new_df.sample(5)

,song_name,video_id,title,artist,release_date,views,likes,comments
796,ASPHALT 8,UTnBD5nRE1Y,"Asphalt 8, New Update 72 (8.2.0) is Here, All ...",Aditya Kataria,2025-02-26T00:26:17Z,1503.0,67.0,20.0
2516,Geronimo,UL_EXAyGCkw,Sheppard - Geronimo (Official Music Video),SheppardVEVO,2014-08-01T07:01:00Z,57711699.0,451528.0,19279.0
3111,Closer to You (feat. Major Lazer),tUq_ksOiuxo,Jung Kook feat. Major Lazer - Closer to You (O...,Major Lazer Official,2023-11-07T15:00:53Z,6724639.0,151241.0,3033.0
198,Deja Vu,cii6ruuycQA,Olivia Rodrigo - deja vu (Official Video),OliviaRodrigoVEVO,2021-04-01T16:00:27Z,504539255.0,6039358.0,157213.0
3829,Night Nurse,K6oYyG0KcvQ,Gregory Isaacs - Night Nurse,Burak Yıldırım,2007-09-06T14:44:16Z,81098962.0,400398.0,13143.0

In [11]:
new_df.isnull().sum()

song_name        0
video_id         0
title            0
artist           0
release_date     0
views            1
likes           28
comments        41
dtype: int64

In [12]:
new_df.drop(new_df[new_df['views'].isnull()].index, inplace=True)
new_df.drop(new_df[new_df['likes'].isnull()].index, inplace=True)

In [13]:
new_df.drop('comments', axis=1, inplace=True)

In [14]:
new_df.isnull().sum()

song_name       0
video_id        0
title           0
artist          0
release_date    0
views           0
likes           0
dtype: int64

In [15]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7178 entries, 0 to 7219
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   song_name     7178 non-null   object
 1   video_id      7178 non-null   object
 2   title         7178 non-null   object
 3   artist        7178 non-null   object
 4   release_date  7178 non-null   object
 5   views         7178 non-null   float64
 6   likes         7178 non-null   float64
dtypes: float64(2), object(5)
memory usage: 448.6+ KB

In [17]:
print(new_df.duplicated().sum())

0

In [ ]:
new_df.to_csv('cleaned_data_yt.csv', index=False)

# Data Understanding and Cleaning (Last fm)

In [23]:
data = data_last_fm.copy()

In [24]:
data.head(5)

,Track,Artist,Listeners,Playcount,Album,Tags,URL
0,When I'm With You,NCT DREAM,41296,660264,NaN,"['House', 'Awesome', 'upbeat', 'Korean', 'k-pop']",https://www.last.fm/music/NCT+DREAM/_/When+I%2...
1,Moonlit Floor (Kiss Me),LISA,164108,2545493,Moonlit Floor (Kiss Me),"['pop', 'dance pop', 'nu-disco', 'Hip-Hop', 'r...",https://www.last.fm/music/Lisa/_/Moonlit+Floor...
2,Who,Jimin,290397,118664117,NaN,"['homosexual', 'soty', 'bots', 'who', 'jimin']",https://www.last.fm/music/jimin/_/Who
3,New Woman (feat. ROSALÍA),"LISA, ROSALÍA",13329,573805,NaN,[],"https://www.last.fm/music/LISA,+ROSAL%C3%8DA/_..."
4,Die With A Smile,"Lady Gaga, Bruno Mars",35802,562233,NaN,"['collab', 'primadonna', 'lady mars']","https://www.last.fm/music/Lady+Gaga,+Bruno+Mar..."

In [ ]:
data = data[['Track', 'Artist', 'Listeners', 'Playcount']]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7211 entries, 0 to 7210
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Track      7211 non-null   object
 1   Artist     7211 non-null   object
 2   Listeners  7211 non-null   int64
 3   Playcount  7211 non-null   int64
dtypes: int64(2), object(2)
memory usage: 225.5+ KB

In [ ]:
data.to_csv('cleaned_data_last_fm.csv', index=False)

# merge dataframe

In [ ]:
spotify = pd.read_csv('/content/cleaned_data_spotify.csv')
youtube = pd.read_csv('/content/cleaned_data_yt.csv')
last_fm = pd.read_csv('/content/cleaned_data_last_fm.csv')

In [ ]:
spotify.columns

Index(['id', 'track_name', 'artist', 'album', 'popularity', 'release_date',
       'spotify_url', 'Genre'],
      dtype='object')

In [ ]:
youtube.columns

Index(['song_name', 'video_id', 'title', 'artist', 'release_date', 'views',
       'likes'],
      dtype='object')

In [ ]:
last_fm.columns

Index(['Track', 'Artist', 'Listeners', 'Playcount'], dtype='object')

In [ ]:
df_fm = last_fm.copy()
df_sp = spotify.copy()
df_yt = youtube.copy()

df_fm.rename(columns={'Track': 'track_name'}, inplace=True)
df_yt.rename(columns={'song_name': 'track_name'}, inplace=True)
df_sp.rename(columns={'track_name': 'track_name'}, inplace=True)

#select column
df_yt = df_yt[['track_name', 'views', 'likes']]
df_sp = df_sp[['track_name', 'popularity', 'artist', 'album', 'release_date']]
df_fm = df_fm[['track_name', 'Listeners', 'Playcount']]

# merg_spo_yt = df_sp.merge(df_yt, on=['track_name', 'artist'], how='left')
merged_left = pd.merge(df_fm, df_sp, on='track_name', how='left')

In [ ]:
merged_left.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7211 entries, 0 to 7210
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_name    7211 non-null   object
 1   Listeners     7211 non-null   int64
 2   Playcount     7211 non-null   int64
 3   popularity    7211 non-null   int64
 4   artist        7211 non-null   object
 5   album         7210 non-null   object
 6   release_date  7211 non-null   object
dtypes: int64(3), object(4)
memory usage: 394.5+ KB

In [ ]:
merged_left[merged_left['album'].isnull()]

     track_name  Listeners  Playcount  popularity  artist album release_date
3079       ABCD     243727    5147537          68  NAYEON   NaN   2024-06-14

In [ ]:
merged_left.loc[3079,'album'] = 'NA'

In [ ]:
merged_final = pd.merge(merged_left, df_yt, on='track_name', how='left')

In [ ]:
merged_cleaned = merged_final.dropna(subset=['views', 'likes'])

In [ ]:
merged_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7169 entries, 0 to 7210
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_name    7169 non-null   object
 1   Listeners     7169 non-null   int64
 2   Playcount     7169 non-null   int64
 3   popularity    7169 non-null   int64
 4   artist        7169 non-null   object
 5   album         7169 non-null   object
 6   release_date  7169 non-null   object
 7   views         7169 non-null   float64
 8   likes         7169 non-null   float64
dtypes: float64(2), int64(3), object(4)
memory usage: 560.1+ KB

In [ ]:

for i in merged_cleaned.index:
  release_date = merged_cleaned.loc[i,'release_date']
  temp = release_date.split('-')
  if len(release_date) == 4:
    merged_cleaned.loc[i,'year'] = temp[0]
    merged_cleaned.loc[i,'month'] = np.NaN
    merged_cleaned.loc[i,'day'] = np.NaN
  elif len(release_date) == 7:
    merged_cleaned.loc[i,'year'] = temp[0]
    merged_cleaned.loc[i,'month'] = temp[1]
    merged_cleaned.loc[i,'day'] = np.NaN
  else:
    merged_cleaned.loc[i,'year'] = temp[0]
    merged_cleaned.loc[i,'month'] = temp[1]
    merged_cleaned.loc[i,'day'] = temp[2]

<ipython-input-119-66781714eb00>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_cleaned.loc[i,'year'] = temp[0]
<ipython-input-119-66781714eb00>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_cleaned.loc[i,'month'] = temp[1]
<ipython-input-119-66781714eb00>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_cleaned.loc[i,'day'] = temp[2]

In [ ]:
merged_cleaned

,track_name,Listeners,Playcount,popularity,artist,album,release_date,views,likes,year,month,day
0,When I'm With You,41296,660264,74,NCT DREAM,DREAMSCAPE,2024-11-11,1356990.0,76411.0,2024,11,11
1,Moonlit Floor (Kiss Me),164108,2545493,79,LISA,Moonlit Floor (Kiss Me),2024-10-03,66200691.0,1310509.0,2024,10,03
2,Who,290397,118664117,86,Jimin,MUSE,2024-07-19,90380936.0,2662194.0,2024,07,19
3,New Woman (feat. ROSALÍA),13329,573805,77,"LISA, ROSALÍA",New Woman (feat. ROSALÍA),2024-08-15,142792624.0,3299299.0,2024,08,15
4,Die With A Smile,35802,562233,97,"Lady Gaga, Bruno Mars",Die With A Smile,2024-08-16,749845365.0,8793461.0,2024,08,16
...,...,...,...,...,...,...,...,...,...,...,...,...
7206,How To Save A Life - Techno Remix,3170,11974,55,Discotekk,How To Save A Life (Techno Remix),2023-09-15,63570.0,763.0,2023,09,15
7207,裸足の季節,3947,27554,33,Seiko Matsuda,BIBLE,1980,43816.0,590.0,1980,NaN,NaN
7208,Light Up the Sky,68134,369364,43,The Prodigy,No Tourists,2018-11-02,12863259.0,88384.0,2018,11,02
7209,Die Welt Brennt,250,1230,48,"Klangkuenstler, Obernauer",Die Welt Brennt,2023-02-03,293598.0,7622.0,2023,02,03
7210,Body Language - Original Remaster,63,201,42,"M.A.N.D.Y., Booka Shade",Body Language,2023-03-31,63870.0,1337.0,2023,03,31

In [ ]:
merged_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7169 entries, 0 to 7210
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_name    7169 non-null   object
 1   Listeners     7169 non-null   int64
 2   Playcount     7169 non-null   int64
 3   popularity    7169 non-null   int64
 4   artist        7169 non-null   object
 5   album         7169 non-null   object
 6   release_date  7169 non-null   object
 7   views         7169 non-null   float64
 8   likes         7169 non-null   float64
 9   year          7169 non-null   object
 10  month         6733 non-null   object
 11  day           6714 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 986.1+ KB

In [ ]:
merged_cleaned.to_csv('merged_data.csv', index=False)